// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIS8O-E8JzEWsfK4vouA-DO_LVrJv-Ol4',
    appId: '1:531654299620:web:ba2ae5905886e6f0f701f1',
    messagingSenderId: '531654299620',
    projectId: 'selaa-2ff93',
    authDomain: 'selaa-2ff93.firebaseapp.com',
    storageBucket: 'selaa-2ff93.appspot.com',
    measurementId: 'G-YPB4LPWH75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDW0q3zhD-VZlORn2vV1S5XDhjaeQf2_U',
    appId: '1:531654299620:android:0f37dbe76663f894f701f1',
    messagingSenderId: '531654299620',
    projectId: 'selaa-2ff93',
    storageBucket: 'selaa-2ff93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjMWNTLsKiHO4PeTqUoD3OBFtdtW97iOg',
    appId: '1:531654299620:ios:abb6c79bd5b806ecf701f1',
    messagingSenderId: '531654299620',
    projectId: 'selaa-2ff93',
    storageBucket: 'selaa-2ff93.appspot.com',
    iosBundleId: 'com.example.selaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjMWNTLsKiHO4PeTqUoD3OBFtdtW97iOg',
    appId: '1:531654299620:ios:006cbabf2c6ad7b8f701f1',
    messagingSenderId: '531654299620',
    projectId: 'selaa-2ff93',
    storageBucket: 'selaa-2ff93.appspot.com',
    iosBundleId: 'com.example.selaa.RunnerTests',
  );
}
