// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8SAu_Ds6KEA2Wg9064dbZMYL6KhZ1jE',
    appId: '1:704459372046:web:68a0887b11318c4c8c6e5f',
    messagingSenderId: '704459372046',
    projectId: 'selaa-93e88',
    authDomain: 'selaa-93e88.firebaseapp.com',
    storageBucket: 'selaa-93e88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDkKi-2GtUrhDbp03eWE-mXmgYozspDWI',
    appId: '1:704459372046:android:deffa518e69cc3928c6e5f',
    messagingSenderId: '704459372046',
    projectId: 'selaa-93e88',
    storageBucket: 'selaa-93e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe6qf7y37mhhX0j2p3WRboEoGyyGvwYTQ',
    appId: '1:704459372046:ios:7c067cb8540815348c6e5f',
    messagingSenderId: '704459372046',
    projectId: 'selaa-93e88',
    storageBucket: 'selaa-93e88.appspot.com',
    iosBundleId: 'com.example.selaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe6qf7y37mhhX0j2p3WRboEoGyyGvwYTQ',
    appId: '1:704459372046:ios:5d7433f9e37308538c6e5f',
    messagingSenderId: '704459372046',
    projectId: 'selaa-93e88',
    storageBucket: 'selaa-93e88.appspot.com',
    iosBundleId: 'com.example.selaa.RunnerTests',
  );
}
